### ISSUE TITLE
Convert gnfinder to use new verification API of gnames

### ISSUE THREAD

**Issue by dimus** [gnames/gnfinder#110]

**Comment by LocoDelAssembly** [comment]
@dimus Is it intended API version to be downgraded from `v1` to `v0`? (Client libraries still expecting `v1` to exist)

**Comment by dimus** [comment]
@LocoDelAssembly well, it is not degraded, it was a way to deal with a mistake I made with API.

I started with API v1 even if gnverifier is at v0, and as such, promised that API will be stable and people can rely that it will be backward compatible.

Then I had to untroduce new features that make API backward incompatible, and instead of making API 2, than API3 and so on  until API is stable. That would mean we have to "pollute" our servers with many versions of gnverifier, and I wanted to keep only 2 for now: v1 for people who use it already, and v0 for all development until gnverifier itself is at v1. Then I will introduce API v2 and start sunsetting process for v1.

**Comment by LocoDelAssembly** [comment]
@dimus but currently `v1` it is completely disabled and returns `Not Found`, right? Current status:
```
rspec
FFFFFFFFFFFFFF.FFF.

Failures:

  1) Gnfinder::Client#ping connects to the server
     Failure/Error: @site['/ping'].get.body
     
     RestClient::NotFound:
       404 Not Found
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
     # ./lib/gnfinder/client.rb:21:in `ping'
     # ./spec/lib/client_spec.rb:9:in `block (3 levels) in <top (required)>'

  2) Gnfinder::Client#version returns version of Go gnfinder
     Failure/Error: resp = @site['/version'].get
     
     RestClient::NotFound:
       404 Not Found
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /home/hernan/.rvm/gems/ruby-3.0.2/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
     # ./lib/gnfinder/client.rb:15:in `gnfinder_version'
     # ./spec/lib/client_spec.rb:15:in `block (3 levels) in <top (required)>'
.
.
.
```
